call pathogen#infect()
syntax on
filetype plugin indent on
"se t_Co=256

"set smartindent
set tabstop=3
set shiftwidth=3
set expandtab

set background=dark
let g:solarized_termcolors=256
colorscheme solarized

set tabstop=3
set shiftwidth=3
set softtabstop=3
set expandtab
set smarttab

set ls=2
