call pathogen#infect()
syntax on
filetype plugin indent on
"se t_Co=256

set background=dark
let g:solarized_termcolors=256
colorscheme solarized

set tabstop=3
set shiftwidth=3
set softtabstop=3
set expandtab
set smarttab

set ls=2

" Automatic toggle of paste/nopaste modes
function! WrapForTmux(s)
  if !exists('$TMUX')
    return a:s
  endif

  let tmux_start = "\<Esc>Ptmux;"
  let tmux_end = "\<Esc>\\"

  return tmux_start . substitute(a:s, "\<Esc>", "\<Esc>\<Esc>", 'g') . tmux_end
endfunction

let &t_SI .= WrapForTmux("\<Esc>[?2004h")
let &t_EI .= WrapForTmux("\<Esc>[?2004l")

function! XTermPasteBegin()
  set pastetoggle=<Esc>[201~
  set paste
  return ""
endfunction

inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()

