---

# Reusable chunks of code
.bootstrap_pipenv_dev: &bootstrap_pipenv_dev |
  pip install pipenv
  pipenv sync --dev  # sync is preferred over install --ignore-pipfile

.alpine_install_standard_packages: &alpine_install_standard_packages |
  apk update
  apk add \
    bash \
    coreutils \
    curl \
    findutils \
    git \
    grep \
    make

stages:
  - lint

# Check for whitespace failures.
check_for_whitespace_errors:
  stage: lint
  image: artifactory.cloud.cas.org/docker-hub/alpine:3.11
  tags:
    - docker
  script:
    - *alpine_install_standard_packages
    - make lint-whitespace

yamllint:
  stage: lint
  image: artifactory.cloud.cas.org/docker-hub/python:3.8.5
  tags:
    - docker
  script:
    - *bootstrap_pipenv_dev
    - make lint-yaml

ansible-lint:
  stage: lint
  image: artifactory.cloud.cas.org/docker-hub/python:3.8.5
  tags:
    - docker
  script:
    - *bootstrap_pipenv_dev
    - make lint-ansible

shellcheck:
  stage: lint
  image: artifactory.cloud.cas.org/docker-hub/alpine:3.11
  tags:
    - docker
  script:
    - *alpine_install_standard_packages
    - curl -sL https://storage.googleapis.com/shellcheck/shellcheck-v0.7.1.linux-x86_64 -o /usr/bin/shellcheck
    - make lint-shellcheck
