---

variables:
  ALPINE_IMAGE: alpine:3.15
  PYTHON_IMAGE: python:3.10
  POETRY_VERSION: 1.1.13

# Reusable chunks of code
.bootstrap_poetry: &bootstrap_poetry |
  pip install "poetry==$POETRY_VERSION"
  pip install "poetry-dynamic-versioning"
  poetry install
  #poetry config experimental.new-installer false  # per https://github.com/python-poetry/poetry/issues/3199

.alpine_setup: &alpine_setup |
  apk --update --no-cache add \
    bash \
    coreutils \
    curl \
    findutils \
    file \
    git \
    grep \
    jq \
    make \
    sed \
    tar

stages:
  - lint

# Check for whitespace failures.
check_for_whitespace_errors:
  stage: lint
  image: $ALPINE_IMAGE
  tags:
    - docker
  script:
    - *alpine_setup
    - make lint-whitespace

yamllint:
  stage: lint
  image: $PYTHON_IMAGE
  tags:
    - docker
  script:
    - *bootstrap_poetry
    - make lint-yaml

ansible-lint:
  stage: lint
  image: $PYTHON_IMAGE
  tags:
    - docker
  script:
    - *bootstrap_poetry
    - make lint-ansible

shellcheck:
  stage: lint
  image: $ALPINE_IMAGE
  tags:
    - docker
  script:
    - *alpine_setup
    - make setup-shellcheck BASE_DIR=/usr/local
    - make lint-shellcheck
