---

- name: "Install pyenv"
  git:
    repo: "https://github.com/pyenv/pyenv.git"
    dest: "{{ pyenv_path }}"
    update: "{{ pyenv_update_git_install }}"

- name: "Install pyenv-virtualenv plugin"
  git:
    repo: "https://github.com/yyuu/pyenv-virtualenv.git"
    dest: "{{ pyenv_path }}/plugins/pyenv-virtualenv"
    update: "{{ pyenv_update_git_install }}"

- name: "Install pyenv-update plugin"
  git:
    repo: "https://github.com/pyenv/pyenv-update.git"
    dest: "{{ pyenv_path }}/plugins/pyenv-update"
    update: "{{ pyenv_update_git_install }}"

- name: "Create bash configuration directory"
  file:
    name: "{{ pyenv_bashrc_path }}"
    state: "directory"
    owner: "{{ pyenv_owner }}"
    mode: "0755"

- name: "Install pyenv bash config"
  template:
    src: "50_pyenv.j2"
    dest: "{{ pyenv_config_path }}"
    owner: "{{ pyenv_owner }}"
    mode: "0755"

- name: "Update Pyenv interpreter list"
  shell: |
    source {{ pyenv_config_path }} && pyenv update
  when: pyenv_update

- name: "Install Python interpreters {{ pyenv_python_versions }}"
  shell: |
    source {{ pyenv_config_path }} && env PYTHON_CONFIGURE_OPTS='{{ pyenv_python_configure_opts }}' pyenv install {{ item }}
  args:
    creates: "{{ pyenv_path }}/versions/{{ item }}/bin/python"
  with_items: "{{ pyenv_python_versions }}"

- name: "Set pyenv global"
  shell: |
    source {{ pyenv_config_path }} && pyenv global {{ pyenv_global }} && pyenv rehash
  when: pyenv_global is defined
