---

starship_version: 0.44.0
starship_release_url: "https://github.com/starship/starship/releases/download/v{{ starship_version }}/starship-x86_64-unknown-linux-gnu.tar.gz"
starship_path: "{{ ansible_env.HOME }}/bin"
starship_owner: "{{ ansible_env.USER }}"
