[directory]
truncation_length = 3
truncate_to_repo = false

#[env_var]
#variable = "OS_CLOUD_PROJECT"
#style = "bold yellow"
#symbol = "  "

[username]
format = "[$user]($style)@"
show_always = true

[hostname]
ssh_only = false

#[character]
#success_symbol = "❯"
#error_symbol = "✖"

#[aws]
#symbol = "  "
